/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    orders: Order;
    'order-items': OrderItem;
    'shop-webhook-events': ShopWebhookEvent;
    'shop-inventory-locks': ShopInventoryLock;
    services: Service;
    treatments: Treatment;
    areas: Area;
    objectives: Objective;
    intents: Intent;
    zones: Zone;
    programs: Program;
    products: Product;
    brands: Brand;
    'brand-lines': BrandLine;
    badges: Badge;
    textures: Texture;
    attributes: Attribute;
    needs: Need;
    'skin-types': SkinType;
    'product-areas': ProductArea;
    'timing-products': TimingProduct;
    promotions: Promotion;
    'routine-templates': RoutineTemplate;
    'routine-template-steps': RoutineTemplateStep;
    'routine-template-step-products': RoutineTemplateStepProduct;
    'routine-steps': RoutineStep;
    'routine-step-rules': RoutineStepRule;
    'brand-line-needs-priority': BrandLineNeedsPriority;
    boosts: Boost;
    exclusions: Exclusion;
    pages: Page;
    posts: Post;
    media: Media;
    users: User;
    'auth-audit-events': AuthAuditEvent;
    'consultation-leads': ConsultationLead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    'shop-webhook-events': ShopWebhookEventsSelect<false> | ShopWebhookEventsSelect<true>;
    'shop-inventory-locks': ShopInventoryLocksSelect<false> | ShopInventoryLocksSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    treatments: TreatmentsSelect<false> | TreatmentsSelect<true>;
    areas: AreasSelect<false> | AreasSelect<true>;
    objectives: ObjectivesSelect<false> | ObjectivesSelect<true>;
    intents: IntentsSelect<false> | IntentsSelect<true>;
    zones: ZonesSelect<false> | ZonesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'brand-lines': BrandLinesSelect<false> | BrandLinesSelect<true>;
    badges: BadgesSelect<false> | BadgesSelect<true>;
    textures: TexturesSelect<false> | TexturesSelect<true>;
    attributes: AttributesSelect<false> | AttributesSelect<true>;
    needs: NeedsSelect<false> | NeedsSelect<true>;
    'skin-types': SkinTypesSelect<false> | SkinTypesSelect<true>;
    'product-areas': ProductAreasSelect<false> | ProductAreasSelect<true>;
    'timing-products': TimingProductsSelect<false> | TimingProductsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'routine-templates': RoutineTemplatesSelect<false> | RoutineTemplatesSelect<true>;
    'routine-template-steps': RoutineTemplateStepsSelect<false> | RoutineTemplateStepsSelect<true>;
    'routine-template-step-products': RoutineTemplateStepProductsSelect<false> | RoutineTemplateStepProductsSelect<true>;
    'routine-steps': RoutineStepsSelect<false> | RoutineStepsSelect<true>;
    'routine-step-rules': RoutineStepRulesSelect<false> | RoutineStepRulesSelect<true>;
    'brand-line-needs-priority': BrandLineNeedsPrioritySelect<false> | BrandLineNeedsPrioritySelect<true>;
    boosts: BoostsSelect<false> | BoostsSelect<true>;
    exclusions: ExclusionsSelect<false> | ExclusionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'auth-audit-events': AuthAuditEventsSelect<false> | AuthAuditEventsSelect<true>;
    'consultation-leads': ConsultationLeadsSelect<false> | ConsultationLeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('it' | 'en' | 'ru') | ('it' | 'en' | 'ru')[];
  globals: {
    'site-settings': SiteSetting;
    'instagram-settings': InstagramSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'instagram-settings': InstagramSettingsSelect<false> | InstagramSettingsSelect<true>;
  };
  locale: 'it' | 'en' | 'ru';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  status: 'pending' | 'paid' | 'failed' | 'cancelled' | 'refunded' | 'fulfilled';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  inventoryCommitted?: boolean | null;
  allocationReleased?: boolean | null;
  paymentProvider: string;
  paymentReference?: string | null;
  currency: string;
  locale: string;
  subtotal: number;
  shippingAmount: number;
  discountAmount: number;
  total: number;
  customerEmail: string;
  customerFirstName: string;
  customerLastName: string;
  customerPhone?: string | null;
  shippingAddress: {
    address: string;
    postalCode: string;
    city: string;
    province: string;
    country: string;
  };
  /**
   * Dati sincronizzazione spedizione Sendcloud.
   */
  sendcloud?: {
    parcelId?: number | null;
    carrierCode?: string | null;
    trackingNumber?: string | null;
    trackingUrl?: string | null;
    labelUrl?: string | null;
    statusMessage?: string | null;
    lastSyncAt?: string | null;
    error?: string | null;
  };
  customer?: (number | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'editor' | 'customer')[];
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  preferences?: {
    marketingOptIn?: boolean | null;
    preferredLocale?: ('it' | 'en' | 'ru') | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  product: number | Product;
  productTitle: string;
  productSlug?: string | null;
  productBrand?: string | null;
  productCoverImage?: string | null;
  currency: string;
  unitPrice: number;
  quantity: number;
  lineTotal: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  active?: boolean | null;
  slug: string;
  sku?: string | null;
  format?: string | null;
  price: number;
  alternatives?:
    | {
        product?: (number | null) | Product;
        sku?: string | null;
        format?: string | null;
        price?: number | null;
        isRefill?: boolean | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  brand?: (number | null) | Brand;
  brandLine?: (number | null) | BrandLine;
  isRefill?: boolean | null;
  featured?: boolean | null;
  coverImage?: (number | null) | Media;
  images?: (number | Media)[] | null;
  usage?: string | null;
  activeIngredients?: string | null;
  results?: string | null;
  /**
   * URL embed (YouTube/Vimeo)
   */
  videoEmbedUrl?: string | null;
  videoUpload?: (number | null) | Media;
  videoPoster?: (number | null) | Media;
  /**
   * Seleziona un media già presente in cover/gallery del prodotto.
   */
  specsMedia?: (number | null) | Media;
  specsGoodFor?: string | null;
  specsFeelsLike?: string | null;
  specsSmellsLike?: string | null;
  specsFYI?: string | null;
  /**
   * Seleziona un media dalla gallery del prodotto.
   */
  includedMedia?: (number | null) | Media;
  includedLabel?: string | null;
  includedDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  includedIngredientsLabel?: string | null;
  includedIngredients?:
    | {
        label?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  includedFooter?: string | null;
  faqMedia?: (number | null) | Media;
  faqTitle?: string | null;
  faqSubtitle?: string | null;
  faqItems?:
    | {
        q?: string | null;
        a?: string | null;
        id?: string | null;
      }[]
    | null;
  needs?: (number | Need)[] | null;
  skinTypePrimary?: (number | null) | SkinType;
  skinTypeSecondary?: (number | SkinType)[] | null;
  textures?: (number | Texture)[] | null;
  productAreas?: (number | ProductArea)[] | null;
  timingProducts?: (number | TimingProduct)[] | null;
  stock?: number | null;
  allocatedStock?: number | null;
  averageCost?: number | null;
  total?: number | null;
  lastDeliveryDate?: string | null;
  deliveries?:
    | {
        lot?: string | null;
        quantity?: number | null;
        costPerUnit?: number | null;
        totalCost?: number | null;
        deliveryDate?: string | null;
        expiryDate?: string | null;
        id?: string | null;
      }[]
    | null;
  stripeProductId?: string | null;
  stripePriceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    heroDesktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    heroMobile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    cardLarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-lines".
 */
export interface BrandLine {
  id: number;
  name: string;
  slug: string;
  brand: number | Brand;
  active?: boolean | null;
  sortOrder?: number | null;
  lineHeadline?: string | null;
  brandLineMedia?: (number | null) | Media;
  description?: string | null;
  usage?: string | null;
  activeIngredients?: string | null;
  results?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "needs".
 */
export interface Need {
  id: number;
  name: string;
  boxTagline?: string | null;
  cardTitle?: string | null;
  cardTagline?: string | null;
  cardMedia?: (number | null) | Media;
  slug: string;
  productArea: number | ProductArea;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-areas".
 */
export interface ProductArea {
  id: number;
  name: string;
  slug: string;
  boxTagline?: string | null;
  cardTitle?: string | null;
  cardTagline?: string | null;
  cardMedia?: (number | null) | Media;
  cardDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skin-types".
 */
export interface SkinType {
  id: number;
  name: string;
  slug: string;
  productArea: number | ProductArea;
  boxTagline?: string | null;
  cardTitle?: string | null;
  cardTagline?: string | null;
  cardMedia?: (number | null) | Media;
  cardDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textures".
 */
export interface Texture {
  id: number;
  name: string;
  boxTagline?: string | null;
  cardTitle?: string | null;
  cardTagline?: string | null;
  cardMedia?: (number | null) | Media;
  slug: string;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timing-products".
 */
export interface TimingProduct {
  id: number;
  name: string;
  slug: string;
  boxTagline?: string | null;
  cardTitle?: string | null;
  cardTagline?: string | null;
  cardMedia?: (number | null) | Media;
  cardDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-webhook-events".
 */
export interface ShopWebhookEvent {
  id: number;
  eventID: string;
  provider: string;
  type: string;
  order?: (number | null) | Order;
  processed: boolean;
  processedAt?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-inventory-locks".
 */
export interface ShopInventoryLock {
  id: number;
  product: number | Product;
  lockToken: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  active?: boolean | null;
  legacyName?: string | null;
  slug: string;
  description?: string | null;
  price: number;
  durationMinutes?: number | null;
  serviceType: 'single' | 'package';
  gallery?:
    | {
        media: number | Media;
        isCover?: boolean | null;
        mediaType?: ('image' | 'video') | null;
        id?: string | null;
      }[]
    | null;
  tagline?: string | null;
  badge?: (number | null) | Badge;
  results?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  indications?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  techProtocolShort?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  downtime?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL embed (YouTube/Vimeo)
   */
  videoEmbedUrl?: string | null;
  videoUpload?: (number | null) | Media;
  /**
   * Seleziona un media dalla gallery del servizio.
   */
  includedMedia?: (number | null) | Media;
  includedDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faqMedia?: (number | null) | Media;
  faqTitle?: string | null;
  faqSubtitle?: string | null;
  faqItems?:
    | {
        q?: string | null;
        a?: string | null;
        id?: string | null;
      }[]
    | null;
  treatments: (number | Treatment)[];
  objective?: (number | null) | Objective;
  area?: (number | null) | Area;
  intent?: (number | null) | Intent;
  zone?: (number | null) | Zone;
  gender?: ('unisex' | 'female' | 'male') | null;
  modality?: ('device' | 'manual' | 'laser' | 'consultation' | 'wax') | null;
  intentCode?: string | null;
  zoneCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges".
 */
export interface Badge {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatments".
 */
export interface Treatment {
  id: number;
  boxName: string;
  boxTagline?: string | null;
  cardName?: string | null;
  cardTagline?: string | null;
  cardMedia?: (number | null) | Media;
  cardDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  reference?:
    | (
        | {
            relationTo: 'objectives';
            value: number | Objective;
          }
        | {
            relationTo: 'areas';
            value: number | Area;
          }
      )[]
    | null;
  description?: string | null;
  heroImage?: (number | null) | Media;
  image?: (number | null) | Media;
  highlightImageLeft?: (number | null) | Media;
  highlightImageRight?: (number | null) | Media;
  highlightLead?: string | null;
  highlightPointOneTitle?: string | null;
  highlightPointOneBody?: string | null;
  highlightPointTwoTitle?: string | null;
  highlightPointTwoBody?: string | null;
  dobGroup?: string | null;
  slug: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objectives".
 */
export interface Objective {
  id: number;
  boxName: string;
  slug: string;
  boxTagline?: string | null;
  cardName?: string | null;
  cardTagline?: string | null;
  cardMedia?: (number | null) | Media;
  cardDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  area: number | Area;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas".
 */
export interface Area {
  id: number;
  name: string;
  slug: string;
  boxTagline?: string | null;
  cardTitle?: string | null;
  cardTagline?: string | null;
  cardMedia?: (number | null) | Media;
  cardDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intents".
 */
export interface Intent {
  id: number;
  code: string;
  label: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zones".
 */
export interface Zone {
  id: number;
  code: string;
  label: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  title: string;
  slug?: string | null;
  price?: number | null;
  currency?: ('EUR' | 'USD') | null;
  description?: string | null;
  heroMedia?: (number | null) | Media;
  steps?:
    | {
        stepType: 'manual' | 'service' | 'product';
        /**
         * Media, titolo e sottotitolo vengono presi dal servizio selezionato.
         */
        stepService?: (number | null) | Service;
        /**
         * Media, titolo e sottotitolo vengono presi dal prodotto selezionato.
         */
        stepProduct?: (number | null) | Product;
        stepHeroMedia?: (number | null) | Media;
        stepDetailMedia?: (number | null) | Media;
        stepTitle?: string | null;
        stepSubtitle?: string | null;
        stepBadge?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes".
 */
export interface Attribute {
  id: number;
  slug: string;
  type: 'boolean' | 'enum' | 'text';
  active?: boolean | null;
  sortOrder?: number | null;
  name: string;
  description?: string | null;
  values?:
    | {
        slug: string;
        sortOrder?: number | null;
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  discountType: 'percent' | 'amount';
  discountValue: number;
  startsAt?: string | null;
  endsAt?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routine-templates".
 */
export interface RoutineTemplate {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  productArea: number | ProductArea;
  timing: number | TimingProduct;
  need: number | Need;
  skinType?: (number | null) | SkinType;
  isMultibrand?: boolean | null;
  brand?: (number | null) | Brand;
  brandLine?: (number | null) | BrandLine;
  active?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routine-template-steps".
 */
export interface RoutineTemplateStep {
  id: number;
  routineTemplate: number | RoutineTemplate;
  routineStep: number | RoutineStep;
  stepOrder: number;
  required?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routine-steps".
 */
export interface RoutineStep {
  id: number;
  name: string;
  slug: string;
  productArea: number | ProductArea;
  description?: string | null;
  stepOrderDefault?: number | null;
  isOptionalDefault?: boolean | null;
  isSystem?: boolean | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routine-template-step-products".
 */
export interface RoutineTemplateStepProduct {
  id: number;
  routineTemplate: number | RoutineTemplate;
  routineStep: number | RoutineStep;
  product: number | Product;
  rank?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routine-step-rules".
 */
export interface RoutineStepRule {
  id: number;
  routineStep: number | RoutineStep;
  timing?: (number | null) | TimingProduct;
  objective?: (number | null) | Objective;
  skinType?: (number | null) | SkinType;
  ruleType: 'require' | 'forbid' | 'warn';
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-line-needs-priority".
 */
export interface BrandLineNeedsPriority {
  id: number;
  brandLine: number | BrandLine;
  need: number | Need;
  score: number;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boosts".
 */
export interface Boost {
  id: number;
  score: number;
  objective?: (number | null) | Objective;
  skinType?: (number | null) | SkinType;
  timing?: (number | null) | TimingProduct;
  routineStep?: (number | null) | RoutineStep;
  product?: (number | null) | Product;
  brand?: (number | null) | Brand;
  brandLine?: (number | null) | BrandLine;
  attribute?: (number | null) | Attribute;
  attributeValueId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exclusions".
 */
export interface Exclusion {
  id: number;
  severity: 'hide' | 'warn';
  reason?: string | null;
  objective?: (number | null) | Objective;
  skinType?: (number | null) | SkinType;
  timing?: (number | null) | TimingProduct;
  routineStep?: (number | null) | RoutineStep;
  product?: (number | null) | Product;
  brand?: (number | null) | Brand;
  brandLine?: (number | null) | BrandLine;
  attribute?: (number | null) | Attribute;
  attributeValueId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Configura solo le pagine esistenti (no categorie).
   */
  pageKey:
    | 'home'
    | 'services'
    | 'shop'
    | 'journal'
    | 'location'
    | 'our-story'
    | 'dob-protocol'
    | 'contact'
    | 'checkout';
  heroTitleMode: 'fixed' | 'dynamic';
  heroStyle: 'style1' | 'style2';
  heroTitle?: string | null;
  heroDescription?: string | null;
  heroMedia?: (number | Media)[] | null;
  /**
   * Titolo Step 1.
   */
  routineBuilderStep1Title?: string | null;
  /**
   * Titolo Step 2.
   */
  routineBuilderStep2Title?: string | null;
  servicesCarousel?: {
    limit?: number | null;
    serviceTypes?: ('single' | 'package')[] | null;
    gender?: ('unisex' | 'female' | 'male')[] | null;
    modality?: ('device' | 'manual' | 'laser' | 'consultation' | 'wax')[] | null;
    treatments?: (number | Treatment)[] | null;
    objective?: (number | Objective)[] | null;
    area?: (number | Area)[] | null;
    intent?: (number | Intent)[] | null;
    zone?: (number | Zone)[] | null;
  };
  checkoutNotice?: string | null;
  protocolSplit?: {
    eyebrow?: string | null;
    steps?:
      | {
          label?: string | null;
          title?: string | null;
          subtitle?: string | null;
          media?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  storyHeroHomeTitle?: string | null;
  storyHeroHomeBody?: string | null;
  storyHeroHomeCtaLabel?: string | null;
  storyHeroHomeCtaHref?: string | null;
  storyHeroHomeMedia?: (number | null) | Media;
  storyHeroTitle?: string | null;
  storyHeroBody?: string | null;
  storyHeroCtaLabel?: string | null;
  storyHeroCtaHref?: string | null;
  storyHeroMedia?: (number | null) | Media;
  storyNoteLabel?: string | null;
  storyNoteBody?: string | null;
  storyNoteCtaLabel?: string | null;
  storyNoteCtaHref?: string | null;
  storyNoteMedia?: (number | null) | Media;
  /**
   * Seleziona il programma da mostrare in homepage.
   */
  homeProgram?: (number | null) | Program;
  productsCarousel?: {
    limit?: number | null;
    needs?: (number | Need)[] | null;
    textures?: (number | Texture)[] | null;
  };
  valuesSection?: {
    items?:
      | {
          label?: string | null;
          title?: string | null;
          ctaLabel?: string | null;
          ctaHref?: string | null;
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  storyValues?: {
    items?:
      | {
          label?: string | null;
          title?: string | null;
          description?: string | null;
          media?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  storyTeam?: {
    title?: string | null;
    description?: string | null;
    items?:
      | {
          name?: string | null;
          role?: string | null;
          bio?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: 'journal' | 'event';
  status: 'draft' | 'published';
  publishedAt?: string | null;
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-audit-events".
 */
export interface AuthAuditEvent {
  id: number;
  eventType: 'login_success' | 'login_failed' | 'forgot_password' | 'reset_password';
  success: boolean;
  email?: string | null;
  user?: (number | null) | User;
  ip?: string | null;
  userAgent?: string | null;
  message?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-leads".
 */
export interface ConsultationLead {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  skinType?: string | null;
  concerns?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  message?: string | null;
  status: 'new' | 'in-progress' | 'closed';
  source?: string | null;
  locale?: string | null;
  pagePath?: string | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'shop-webhook-events';
        value: number | ShopWebhookEvent;
      } | null)
    | ({
        relationTo: 'shop-inventory-locks';
        value: number | ShopInventoryLock;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'treatments';
        value: number | Treatment;
      } | null)
    | ({
        relationTo: 'areas';
        value: number | Area;
      } | null)
    | ({
        relationTo: 'objectives';
        value: number | Objective;
      } | null)
    | ({
        relationTo: 'intents';
        value: number | Intent;
      } | null)
    | ({
        relationTo: 'zones';
        value: number | Zone;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'brand-lines';
        value: number | BrandLine;
      } | null)
    | ({
        relationTo: 'badges';
        value: number | Badge;
      } | null)
    | ({
        relationTo: 'textures';
        value: number | Texture;
      } | null)
    | ({
        relationTo: 'attributes';
        value: number | Attribute;
      } | null)
    | ({
        relationTo: 'needs';
        value: number | Need;
      } | null)
    | ({
        relationTo: 'skin-types';
        value: number | SkinType;
      } | null)
    | ({
        relationTo: 'product-areas';
        value: number | ProductArea;
      } | null)
    | ({
        relationTo: 'timing-products';
        value: number | TimingProduct;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'routine-templates';
        value: number | RoutineTemplate;
      } | null)
    | ({
        relationTo: 'routine-template-steps';
        value: number | RoutineTemplateStep;
      } | null)
    | ({
        relationTo: 'routine-template-step-products';
        value: number | RoutineTemplateStepProduct;
      } | null)
    | ({
        relationTo: 'routine-steps';
        value: number | RoutineStep;
      } | null)
    | ({
        relationTo: 'routine-step-rules';
        value: number | RoutineStepRule;
      } | null)
    | ({
        relationTo: 'brand-line-needs-priority';
        value: number | BrandLineNeedsPriority;
      } | null)
    | ({
        relationTo: 'boosts';
        value: number | Boost;
      } | null)
    | ({
        relationTo: 'exclusions';
        value: number | Exclusion;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'auth-audit-events';
        value: number | AuthAuditEvent;
      } | null)
    | ({
        relationTo: 'consultation-leads';
        value: number | ConsultationLead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  paymentStatus?: T;
  inventoryCommitted?: T;
  allocationReleased?: T;
  paymentProvider?: T;
  paymentReference?: T;
  currency?: T;
  locale?: T;
  subtotal?: T;
  shippingAmount?: T;
  discountAmount?: T;
  total?: T;
  customerEmail?: T;
  customerFirstName?: T;
  customerLastName?: T;
  customerPhone?: T;
  shippingAddress?:
    | T
    | {
        address?: T;
        postalCode?: T;
        city?: T;
        province?: T;
        country?: T;
      };
  sendcloud?:
    | T
    | {
        parcelId?: T;
        carrierCode?: T;
        trackingNumber?: T;
        trackingUrl?: T;
        labelUrl?: T;
        statusMessage?: T;
        lastSyncAt?: T;
        error?: T;
      };
  customer?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  productTitle?: T;
  productSlug?: T;
  productBrand?: T;
  productCoverImage?: T;
  currency?: T;
  unitPrice?: T;
  quantity?: T;
  lineTotal?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-webhook-events_select".
 */
export interface ShopWebhookEventsSelect<T extends boolean = true> {
  eventID?: T;
  provider?: T;
  type?: T;
  order?: T;
  processed?: T;
  processedAt?: T;
  payload?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-inventory-locks_select".
 */
export interface ShopInventoryLocksSelect<T extends boolean = true> {
  product?: T;
  lockToken?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  active?: T;
  legacyName?: T;
  slug?: T;
  description?: T;
  price?: T;
  durationMinutes?: T;
  serviceType?: T;
  gallery?:
    | T
    | {
        media?: T;
        isCover?: T;
        mediaType?: T;
        id?: T;
      };
  tagline?: T;
  badge?: T;
  results?: T;
  indications?: T;
  techProtocolShort?: T;
  downtime?: T;
  videoEmbedUrl?: T;
  videoUpload?: T;
  includedMedia?: T;
  includedDescription?: T;
  faqMedia?: T;
  faqTitle?: T;
  faqSubtitle?: T;
  faqItems?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  treatments?: T;
  objective?: T;
  area?: T;
  intent?: T;
  zone?: T;
  gender?: T;
  modality?: T;
  intentCode?: T;
  zoneCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatments_select".
 */
export interface TreatmentsSelect<T extends boolean = true> {
  boxName?: T;
  boxTagline?: T;
  cardName?: T;
  cardTagline?: T;
  cardMedia?: T;
  cardDescription?: T;
  reference?: T;
  description?: T;
  heroImage?: T;
  image?: T;
  highlightImageLeft?: T;
  highlightImageRight?: T;
  highlightLead?: T;
  highlightPointOneTitle?: T;
  highlightPointOneBody?: T;
  highlightPointTwoTitle?: T;
  highlightPointTwoBody?: T;
  dobGroup?: T;
  slug?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas_select".
 */
export interface AreasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  boxTagline?: T;
  cardTitle?: T;
  cardTagline?: T;
  cardMedia?: T;
  cardDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "objectives_select".
 */
export interface ObjectivesSelect<T extends boolean = true> {
  boxName?: T;
  slug?: T;
  boxTagline?: T;
  cardName?: T;
  cardTagline?: T;
  cardMedia?: T;
  cardDescription?: T;
  area?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intents_select".
 */
export interface IntentsSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zones_select".
 */
export interface ZonesSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  price?: T;
  currency?: T;
  description?: T;
  heroMedia?: T;
  steps?:
    | T
    | {
        stepType?: T;
        stepService?: T;
        stepProduct?: T;
        stepHeroMedia?: T;
        stepDetailMedia?: T;
        stepTitle?: T;
        stepSubtitle?: T;
        stepBadge?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  active?: T;
  slug?: T;
  sku?: T;
  format?: T;
  price?: T;
  alternatives?:
    | T
    | {
        product?: T;
        sku?: T;
        format?: T;
        price?: T;
        isRefill?: T;
        id?: T;
      };
  description?: T;
  brand?: T;
  brandLine?: T;
  isRefill?: T;
  featured?: T;
  coverImage?: T;
  images?: T;
  usage?: T;
  activeIngredients?: T;
  results?: T;
  videoEmbedUrl?: T;
  videoUpload?: T;
  videoPoster?: T;
  specsMedia?: T;
  specsGoodFor?: T;
  specsFeelsLike?: T;
  specsSmellsLike?: T;
  specsFYI?: T;
  includedMedia?: T;
  includedLabel?: T;
  includedDescription?: T;
  includedIngredientsLabel?: T;
  includedIngredients?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  includedFooter?: T;
  faqMedia?: T;
  faqTitle?: T;
  faqSubtitle?: T;
  faqItems?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  needs?: T;
  skinTypePrimary?: T;
  skinTypeSecondary?: T;
  textures?: T;
  productAreas?: T;
  timingProducts?: T;
  stock?: T;
  allocatedStock?: T;
  averageCost?: T;
  total?: T;
  lastDeliveryDate?: T;
  deliveries?:
    | T
    | {
        lot?: T;
        quantity?: T;
        costPerUnit?: T;
        totalCost?: T;
        deliveryDate?: T;
        expiryDate?: T;
        id?: T;
      };
  stripeProductId?: T;
  stripePriceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-lines_select".
 */
export interface BrandLinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  brand?: T;
  active?: T;
  sortOrder?: T;
  lineHeadline?: T;
  brandLineMedia?: T;
  description?: T;
  usage?: T;
  activeIngredients?: T;
  results?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "badges_select".
 */
export interface BadgesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textures_select".
 */
export interface TexturesSelect<T extends boolean = true> {
  name?: T;
  boxTagline?: T;
  cardTitle?: T;
  cardTagline?: T;
  cardMedia?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes_select".
 */
export interface AttributesSelect<T extends boolean = true> {
  slug?: T;
  type?: T;
  active?: T;
  sortOrder?: T;
  name?: T;
  description?: T;
  values?:
    | T
    | {
        slug?: T;
        sortOrder?: T;
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "needs_select".
 */
export interface NeedsSelect<T extends boolean = true> {
  name?: T;
  boxTagline?: T;
  cardTitle?: T;
  cardTagline?: T;
  cardMedia?: T;
  slug?: T;
  productArea?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skin-types_select".
 */
export interface SkinTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  productArea?: T;
  boxTagline?: T;
  cardTitle?: T;
  cardTagline?: T;
  cardMedia?: T;
  cardDescription?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-areas_select".
 */
export interface ProductAreasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  boxTagline?: T;
  cardTitle?: T;
  cardTagline?: T;
  cardMedia?: T;
  cardDescription?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timing-products_select".
 */
export interface TimingProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  boxTagline?: T;
  cardTitle?: T;
  cardTagline?: T;
  cardMedia?: T;
  cardDescription?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  discountType?: T;
  discountValue?: T;
  startsAt?: T;
  endsAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routine-templates_select".
 */
export interface RoutineTemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  productArea?: T;
  timing?: T;
  need?: T;
  skinType?: T;
  isMultibrand?: T;
  brand?: T;
  brandLine?: T;
  active?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routine-template-steps_select".
 */
export interface RoutineTemplateStepsSelect<T extends boolean = true> {
  routineTemplate?: T;
  routineStep?: T;
  stepOrder?: T;
  required?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routine-template-step-products_select".
 */
export interface RoutineTemplateStepProductsSelect<T extends boolean = true> {
  routineTemplate?: T;
  routineStep?: T;
  product?: T;
  rank?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routine-steps_select".
 */
export interface RoutineStepsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  productArea?: T;
  description?: T;
  stepOrderDefault?: T;
  isOptionalDefault?: T;
  isSystem?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routine-step-rules_select".
 */
export interface RoutineStepRulesSelect<T extends boolean = true> {
  routineStep?: T;
  timing?: T;
  objective?: T;
  skinType?: T;
  ruleType?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-line-needs-priority_select".
 */
export interface BrandLineNeedsPrioritySelect<T extends boolean = true> {
  brandLine?: T;
  need?: T;
  score?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boosts_select".
 */
export interface BoostsSelect<T extends boolean = true> {
  score?: T;
  objective?: T;
  skinType?: T;
  timing?: T;
  routineStep?: T;
  product?: T;
  brand?: T;
  brandLine?: T;
  attribute?: T;
  attributeValueId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exclusions_select".
 */
export interface ExclusionsSelect<T extends boolean = true> {
  severity?: T;
  reason?: T;
  objective?: T;
  skinType?: T;
  timing?: T;
  routineStep?: T;
  product?: T;
  brand?: T;
  brandLine?: T;
  attribute?: T;
  attributeValueId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageKey?: T;
  heroTitleMode?: T;
  heroStyle?: T;
  heroTitle?: T;
  heroDescription?: T;
  heroMedia?: T;
  routineBuilderStep1Title?: T;
  routineBuilderStep2Title?: T;
  servicesCarousel?:
    | T
    | {
        limit?: T;
        serviceTypes?: T;
        gender?: T;
        modality?: T;
        treatments?: T;
        objective?: T;
        area?: T;
        intent?: T;
        zone?: T;
      };
  checkoutNotice?: T;
  protocolSplit?:
    | T
    | {
        eyebrow?: T;
        steps?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              media?: T;
              id?: T;
            };
      };
  storyHeroHomeTitle?: T;
  storyHeroHomeBody?: T;
  storyHeroHomeCtaLabel?: T;
  storyHeroHomeCtaHref?: T;
  storyHeroHomeMedia?: T;
  storyHeroTitle?: T;
  storyHeroBody?: T;
  storyHeroCtaLabel?: T;
  storyHeroCtaHref?: T;
  storyHeroMedia?: T;
  storyNoteLabel?: T;
  storyNoteBody?: T;
  storyNoteCtaLabel?: T;
  storyNoteCtaHref?: T;
  storyNoteMedia?: T;
  homeProgram?: T;
  productsCarousel?:
    | T
    | {
        limit?: T;
        needs?: T;
        textures?: T;
      };
  valuesSection?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              title?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
            };
        media?: T;
      };
  storyValues?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              title?: T;
              description?: T;
              media?: T;
              id?: T;
            };
      };
  storyTeam?:
    | T
    | {
        title?: T;
        description?: T;
        items?:
          | T
          | {
              name?: T;
              role?: T;
              bio?: T;
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  status?: T;
  publishedAt?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        heroDesktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        heroMobile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        cardLarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  preferences?:
    | T
    | {
        marketingOptIn?: T;
        preferredLocale?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth-audit-events_select".
 */
export interface AuthAuditEventsSelect<T extends boolean = true> {
  eventType?: T;
  success?: T;
  email?: T;
  user?: T;
  ip?: T;
  userAgent?: T;
  message?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-leads_select".
 */
export interface ConsultationLeadsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  skinType?: T;
  concerns?:
    | T
    | {
        value?: T;
        id?: T;
      };
  message?: T;
  status?: T;
  source?: T;
  locale?: T;
  pagePath?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  address?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
  };
  authLayout?: {
    visualOverlay?: string | null;
    visualImage?: (number | null) | Media;
    visualImageAlt?: string | null;
  };
  /**
   * Configurazione SMTP per invio email. In produzione mantieni sincronizzati questi valori con le variabili ambiente.
   */
  smtp?: {
    host?: string | null;
    port?: number | null;
    secure?: boolean | null;
    user?: string | null;
    pass?: string | null;
    from?: string | null;
  };
  /**
   * Configurazione Stripe checkout/webhook. In produzione mantieni sincronizzati questi valori con le variabili ambiente.
   */
  stripe?: {
    secretKey?: string | null;
    webhookSecret?: string | null;
    publishableKey?: string | null;
  };
  /**
   * Configurazione Sendcloud API per spedizioni. Le chiavi sono usate lato server.
   */
  sendcloud?: {
    publicKey?: string | null;
    secretKey?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-settings".
 */
export interface InstagramSetting {
  id: number;
  enabled?: boolean | null;
  /**
   * Instagram Basic Display access token.
   */
  accessToken?: string | null;
  limit?: number | null;
  revalidateSeconds?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  address?: T;
  phone?: T;
  whatsapp?: T;
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
      };
  authLayout?:
    | T
    | {
        visualOverlay?: T;
        visualImage?: T;
        visualImageAlt?: T;
      };
  smtp?:
    | T
    | {
        host?: T;
        port?: T;
        secure?: T;
        user?: T;
        pass?: T;
        from?: T;
      };
  stripe?:
    | T
    | {
        secretKey?: T;
        webhookSecret?: T;
        publishableKey?: T;
      };
  sendcloud?:
    | T
    | {
        publicKey?: T;
        secretKey?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram-settings_select".
 */
export interface InstagramSettingsSelect<T extends boolean = true> {
  enabled?: T;
  accessToken?: T;
  limit?: T;
  revalidateSeconds?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}