/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  serial,
  varchar,
  timestamp,
  numeric,
  boolean,
  type AnyPgColumn,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum__locales = pgEnum('enum__locales', ['it', 'en', 'ru'])
export const enum_users_roles = pgEnum('enum_users_roles', ['admin', 'editor'])
export const enum_products_currency = pgEnum('enum_products_currency', ['EUR'])
export const enum_services_service_type = pgEnum('enum_services_service_type', [
  'single',
  'package',
])
export const enum_services_gender = pgEnum('enum_services_gender', ['unisex', 'female', 'male'])
export const enum_services_modality = pgEnum('enum_services_modality', [
  'device',
  'manual',
  'laser',
  'consultation',
  'wax',
])
export const enum_promotions_discount_type = pgEnum('enum_promotions_discount_type', [
  'percent',
  'amount',
])
export const enum_posts_category = pgEnum('enum_posts_category', ['journal', 'event'])
export const enum_posts_status = pgEnum('enum_posts_status', ['draft', 'published'])
export const enum_pages_page_key = pgEnum('enum_pages_page_key', [
  'home',
  'services',
  'shop',
  'journal',
  'location',
  'our-story',
  'contact',
])
export const enum_pages_hero_title_mode = pgEnum('enum_pages_hero_title_mode', ['fixed', 'dynamic'])
export const enum_pages_hero_style = pgEnum('enum_pages_hero_style', ['style1', 'style2'])

export const users_roles = pgTable(
  'users_roles',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_users_roles('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('users_roles_order_idx').on(columns.order),
    index('users_roles_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [users.id],
      name: 'users_roles_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const products = pgTable(
  'products',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    brand: varchar('brand'),
    price: numeric('price', { mode: 'number' }).notNull(),
    currency: enum_products_currency('currency').notNull().default('EUR'),
    sku: varchar('sku'),
    stock: numeric('stock', { mode: 'number' }).default(0),
    lot: varchar('lot'),
    expiryDate: timestamp('expiry_date', { mode: 'string', withTimezone: true, precision: 3 }),
    averageCost: numeric('average_cost', { mode: 'number' }),
    lastCost: numeric('last_cost', { mode: 'number' }),
    residualTotal: numeric('residual_total', { mode: 'number' }),
    total: numeric('total', { mode: 'number' }),
    coverImage: integer('cover_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    featured: boolean('featured').default(false),
    active: boolean('active').default(true),
    stripeProductId: varchar('stripe_product_id'),
    stripePriceId: varchar('stripe_price_id'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('products_slug_idx').on(columns.slug),
    index('products_brand_idx').on(columns.brand),
    uniqueIndex('products_sku_idx').on(columns.sku),
    index('products_cover_image_idx').on(columns.coverImage),
    index('products_updated_at_idx').on(columns.updatedAt),
    index('products_created_at_idx').on(columns.createdAt),
  ],
)

export const products_locales = pgTable(
  'products_locales',
  {
    title: varchar('title').notNull(),
    description: varchar('description'),
    usage: varchar('usage'),
    activeIngredients: varchar('active_ingredients'),
    results: varchar('results'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('products_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_rels = pgTable(
  'products_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    needsID: integer('needs_id'),
    categoriesID: integer('categories_id'),
    linesID: integer('lines_id'),
    texturesID: integer('textures_id'),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('products_rels_order_idx').on(columns.order),
    index('products_rels_parent_idx').on(columns.parent),
    index('products_rels_path_idx').on(columns.path),
    index('products_rels_needs_id_idx').on(columns.needsID),
    index('products_rels_categories_id_idx').on(columns.categoriesID),
    index('products_rels_lines_id_idx').on(columns.linesID),
    index('products_rels_textures_id_idx').on(columns.texturesID),
    index('products_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['needsID']],
      foreignColumns: [needs.id],
      name: 'products_rels_needs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'products_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['linesID']],
      foreignColumns: [lines.id],
      name: 'products_rels_lines_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['texturesID']],
      foreignColumns: [textures.id],
      name: 'products_rels_textures_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'products_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const needs = pgTable(
  'needs',
  {
    id: serial('id').primaryKey(),
    cardMedia: integer('card_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    slug: varchar('slug').notNull(),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('needs_card_media_idx').on(columns.cardMedia),
    uniqueIndex('needs_slug_idx').on(columns.slug),
    index('needs_updated_at_idx').on(columns.updatedAt),
    index('needs_created_at_idx').on(columns.createdAt),
  ],
)

export const needs_locales = pgTable(
  'needs_locales',
  {
    name: varchar('name').notNull(),
    boxTagline: varchar('box_tagline'),
    cardTitle: varchar('card_title'),
    cardTagline: varchar('card_tagline'),
    description: varchar('description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('needs_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [needs.id],
      name: 'needs_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    cardMedia: integer('card_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    slug: varchar('slug').notNull(),
    parent: integer('parent_id').references((): AnyPgColumn => categories.id, {
      onDelete: 'set null',
    }),
    isMakeupRoot: boolean('is_makeup_root').default(false),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('categories_card_media_idx').on(columns.cardMedia),
    uniqueIndex('categories_slug_idx').on(columns.slug),
    index('categories_parent_idx').on(columns.parent),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
)

export const categories_locales = pgTable(
  'categories_locales',
  {
    name: varchar('name').notNull(),
    boxTagline: varchar('box_tagline'),
    cardTitle: varchar('card_title'),
    cardTagline: varchar('card_tagline'),
    description: varchar('description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('categories_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [categories.id],
      name: 'categories_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const lines = pgTable(
  'lines',
  {
    id: serial('id').primaryKey(),
    cardMedia: integer('card_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    slug: varchar('slug').notNull(),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('lines_card_media_idx').on(columns.cardMedia),
    uniqueIndex('lines_slug_idx').on(columns.slug),
    index('lines_updated_at_idx').on(columns.updatedAt),
    index('lines_created_at_idx').on(columns.createdAt),
  ],
)

export const lines_locales = pgTable(
  'lines_locales',
  {
    name: varchar('name').notNull(),
    boxTagline: varchar('box_tagline'),
    cardTitle: varchar('card_title'),
    cardTagline: varchar('card_tagline'),
    description: varchar('description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('lines_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [lines.id],
      name: 'lines_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const textures = pgTable(
  'textures',
  {
    id: serial('id').primaryKey(),
    cardMedia: integer('card_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    slug: varchar('slug').notNull(),
    order: numeric('order', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('textures_card_media_idx').on(columns.cardMedia),
    uniqueIndex('textures_slug_idx').on(columns.slug),
    index('textures_updated_at_idx').on(columns.updatedAt),
    index('textures_created_at_idx').on(columns.createdAt),
  ],
)

export const textures_locales = pgTable(
  'textures_locales',
  {
    name: varchar('name').notNull(),
    boxTagline: varchar('box_tagline'),
    cardTitle: varchar('card_title'),
    cardTagline: varchar('card_tagline'),
    description: varchar('description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('textures_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [textures.id],
      name: 'textures_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const areas = pgTable(
  'areas',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    cardMedia: integer('card_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('areas_slug_idx').on(columns.slug),
    index('areas_card_media_idx').on(columns.cardMedia),
    index('areas_updated_at_idx').on(columns.updatedAt),
    index('areas_created_at_idx').on(columns.createdAt),
  ],
)

export const areas_locales = pgTable(
  'areas_locales',
  {
    name: varchar('name').notNull(),
    boxTagline: varchar('box_tagline'),
    cardTitle: varchar('card_title'),
    cardTagline: varchar('card_tagline'),
    cardDescription: jsonb('card_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('areas_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [areas.id],
      name: 'areas_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const objectives = pgTable(
  'objectives',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    cardMedia: integer('card_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    area: integer('area_id')
      .notNull()
      .references(() => areas.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('objectives_slug_idx').on(columns.slug),
    index('objectives_card_media_idx').on(columns.cardMedia),
    index('objectives_area_idx').on(columns.area),
    index('objectives_updated_at_idx').on(columns.updatedAt),
    index('objectives_created_at_idx').on(columns.createdAt),
  ],
)

export const objectives_locales = pgTable(
  'objectives_locales',
  {
    boxName: varchar('box_name').notNull(),
    boxTagline: varchar('box_tagline'),
    cardName: varchar('card_name'),
    cardTagline: varchar('card_tagline'),
    cardDescription: jsonb('card_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('objectives_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [objectives.id],
      name: 'objectives_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const intents = pgTable(
  'intents',
  {
    id: serial('id').primaryKey(),
    code: varchar('code').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('intents_code_idx').on(columns.code),
    index('intents_updated_at_idx').on(columns.updatedAt),
    index('intents_created_at_idx').on(columns.createdAt),
  ],
)

export const intents_locales = pgTable(
  'intents_locales',
  {
    label: varchar('label').notNull(),
    description: varchar('description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('intents_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [intents.id],
      name: 'intents_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const zones = pgTable(
  'zones',
  {
    id: serial('id').primaryKey(),
    code: varchar('code').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('zones_code_idx').on(columns.code),
    index('zones_updated_at_idx').on(columns.updatedAt),
    index('zones_created_at_idx').on(columns.createdAt),
  ],
)

export const zones_locales = pgTable(
  'zones_locales',
  {
    label: varchar('label').notNull(),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('zones_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [zones.id],
      name: 'zones_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const treatments = pgTable(
  'treatments',
  {
    id: serial('id').primaryKey(),
    cardMedia: integer('card_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    heroImage: integer('hero_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    highlightImageLeft: integer('highlight_image_left_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    highlightImageRight: integer('highlight_image_right_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    dobGroup: varchar('dob_group'),
    slug: varchar('slug').notNull(),
    active: boolean('active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('treatments_card_media_idx').on(columns.cardMedia),
    index('treatments_hero_image_idx').on(columns.heroImage),
    index('treatments_image_idx').on(columns.image),
    index('treatments_highlight_image_left_idx').on(columns.highlightImageLeft),
    index('treatments_highlight_image_right_idx').on(columns.highlightImageRight),
    uniqueIndex('treatments_slug_idx').on(columns.slug),
    index('treatments_updated_at_idx').on(columns.updatedAt),
    index('treatments_created_at_idx').on(columns.createdAt),
  ],
)

export const treatments_locales = pgTable(
  'treatments_locales',
  {
    boxName: varchar('box_name').notNull(),
    boxTagline: varchar('box_tagline'),
    cardName: varchar('card_name'),
    cardTagline: varchar('card_tagline'),
    cardDescription: jsonb('card_description'),
    description: varchar('description'),
    highlightLead: varchar('highlight_lead'),
    highlightPointOneTitle: varchar('highlight_point_one_title'),
    highlightPointOneBody: varchar('highlight_point_one_body'),
    highlightPointTwoTitle: varchar('highlight_point_two_title'),
    highlightPointTwoBody: varchar('highlight_point_two_body'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('treatments_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [treatments.id],
      name: 'treatments_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const treatments_rels = pgTable(
  'treatments_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    objectivesID: integer('objectives_id'),
    areasID: integer('areas_id'),
  },
  (columns) => [
    index('treatments_rels_order_idx').on(columns.order),
    index('treatments_rels_parent_idx').on(columns.parent),
    index('treatments_rels_path_idx').on(columns.path),
    index('treatments_rels_objectives_id_idx').on(columns.objectivesID),
    index('treatments_rels_areas_id_idx').on(columns.areasID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [treatments.id],
      name: 'treatments_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['objectivesID']],
      foreignColumns: [objectives.id],
      name: 'treatments_rels_objectives_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['areasID']],
      foreignColumns: [areas.id],
      name: 'treatments_rels_areas_fk',
    }).onDelete('cascade'),
  ],
)

export const services = pgTable(
  'services',
  {
    id: serial('id').primaryKey(),
    category: integer('category_id')
      .notNull()
      .references(() => treatments.id, {
        onDelete: 'set null',
      }),
    objective: integer('objective_id').references(() => objectives.id, {
      onDelete: 'set null',
    }),
    area: integer('area_id').references(() => areas.id, {
      onDelete: 'set null',
    }),
    slug: varchar('slug').notNull(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    price: numeric('price', { mode: 'number' }).notNull(),
    durationMinutes: numeric('duration_minutes', { mode: 'number' }),
    serviceType: enum_services_service_type('service_type').notNull().default('single'),
    gender: enum_services_gender('gender'),
    modality: enum_services_modality('modality'),
    intent: integer('intent_id').references(() => intents.id, {
      onDelete: 'set null',
    }),
    zone: integer('zone_id').references(() => zones.id, {
      onDelete: 'set null',
    }),
    intentCode: varchar('intent_code'),
    zoneCode: varchar('zone_code'),
    externalId: numeric('external_id', { mode: 'number' }),
    active: boolean('active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('services_category_idx').on(columns.category),
    index('services_objective_idx').on(columns.objective),
    index('services_area_idx').on(columns.area),
    uniqueIndex('services_slug_idx').on(columns.slug),
    index('services_image_idx').on(columns.image),
    index('services_intent_idx').on(columns.intent),
    index('services_zone_idx').on(columns.zone),
    uniqueIndex('services_external_id_idx').on(columns.externalId),
    index('services_updated_at_idx').on(columns.updatedAt),
    index('services_created_at_idx').on(columns.createdAt),
  ],
)

export const services_locales = pgTable(
  'services_locales',
  {
    name: varchar('name').notNull(),
    description: varchar('description'),
    duration: varchar('duration'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('services_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [services.id],
      name: 'services_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const services_rels = pgTable(
  'services_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    treatmentsID: integer('treatments_id'),
  },
  (columns) => [
    index('services_rels_order_idx').on(columns.order),
    index('services_rels_parent_idx').on(columns.parent),
    index('services_rels_path_idx').on(columns.path),
    index('services_rels_treatments_id_idx').on(columns.treatmentsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [services.id],
      name: 'services_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['treatmentsID']],
      foreignColumns: [treatments.id],
      name: 'services_rels_treatments_fk',
    }).onDelete('cascade'),
  ],
)

export const promotions = pgTable(
  'promotions',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    discountType: enum_promotions_discount_type('discount_type').notNull(),
    discountValue: numeric('discount_value', { mode: 'number' }).notNull(),
    startsAt: timestamp('starts_at', { mode: 'string', withTimezone: true, precision: 3 }),
    endsAt: timestamp('ends_at', { mode: 'string', withTimezone: true, precision: 3 }),
    active: boolean('active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('promotions_slug_idx').on(columns.slug),
    index('promotions_updated_at_idx').on(columns.updatedAt),
    index('promotions_created_at_idx').on(columns.createdAt),
  ],
)

export const promotions_locales = pgTable(
  'promotions_locales',
  {
    title: varchar('title').notNull(),
    description: varchar('description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('promotions_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [promotions.id],
      name: 'promotions_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const programs_items = pgTable(
  'programs_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    itemImage: integer('item_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('programs_items_order_idx').on(columns._order),
    index('programs_items_parent_id_idx').on(columns._parentID),
    index('programs_items_item_image_idx').on(columns.itemImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [programs.id],
      name: 'programs_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const programs_items_locales = pgTable(
  'programs_items_locales',
  {
    itemTitle: varchar('item_title'),
    itemDescription: varchar('item_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: varchar('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('programs_items_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [programs_items.id],
      name: 'programs_items_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const programs = pgTable(
  'programs',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('programs_updated_at_idx').on(columns.updatedAt),
    index('programs_created_at_idx').on(columns.createdAt),
  ],
)

export const programs_locales = pgTable(
  'programs_locales',
  {
    title: varchar('title').notNull(),
    description: varchar('description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('programs_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [programs.id],
      name: 'programs_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const programs_rels = pgTable(
  'programs_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    servicesID: integer('services_id'),
    treatmentsID: integer('treatments_id'),
    areasID: integer('areas_id'),
    objectivesID: integer('objectives_id'),
    promotionsID: integer('promotions_id'),
    productsID: integer('products_id'),
    needsID: integer('needs_id'),
    categoriesID: integer('categories_id'),
    linesID: integer('lines_id'),
    texturesID: integer('textures_id'),
  },
  (columns) => [
    index('programs_rels_order_idx').on(columns.order),
    index('programs_rels_parent_idx').on(columns.parent),
    index('programs_rels_path_idx').on(columns.path),
    index('programs_rels_services_id_idx').on(columns.servicesID),
    index('programs_rels_treatments_id_idx').on(columns.treatmentsID),
    index('programs_rels_areas_id_idx').on(columns.areasID),
    index('programs_rels_objectives_id_idx').on(columns.objectivesID),
    index('programs_rels_promotions_id_idx').on(columns.promotionsID),
    index('programs_rels_products_id_idx').on(columns.productsID),
    index('programs_rels_needs_id_idx').on(columns.needsID),
    index('programs_rels_categories_id_idx').on(columns.categoriesID),
    index('programs_rels_lines_id_idx').on(columns.linesID),
    index('programs_rels_textures_id_idx').on(columns.texturesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [programs.id],
      name: 'programs_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['servicesID']],
      foreignColumns: [services.id],
      name: 'programs_rels_services_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['treatmentsID']],
      foreignColumns: [treatments.id],
      name: 'programs_rels_treatments_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['areasID']],
      foreignColumns: [areas.id],
      name: 'programs_rels_areas_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['objectivesID']],
      foreignColumns: [objectives.id],
      name: 'programs_rels_objectives_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['promotionsID']],
      foreignColumns: [promotions.id],
      name: 'programs_rels_promotions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'programs_rels_products_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['needsID']],
      foreignColumns: [needs.id],
      name: 'programs_rels_needs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'programs_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['linesID']],
      foreignColumns: [lines.id],
      name: 'programs_rels_lines_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['texturesID']],
      foreignColumns: [textures.id],
      name: 'programs_rels_textures_fk',
    }).onDelete('cascade'),
  ],
)

export const posts = pgTable(
  'posts',
  {
    id: serial('id').primaryKey(),
    slug: varchar('slug').notNull(),
    category: enum_posts_category('category').notNull().default('journal'),
    status: enum_posts_status('status').notNull().default('draft'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    coverImage: integer('cover_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('posts_slug_idx').on(columns.slug),
    index('posts_cover_image_idx').on(columns.coverImage),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt),
  ],
)

export const posts_locales = pgTable(
  'posts_locales',
  {
    title: varchar('title').notNull(),
    excerpt: varchar('excerpt'),
    content: jsonb('content'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('posts_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [posts.id],
      name: 'posts_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    pageKey: enum_pages_page_key('page_key').notNull(),
    heroTitleMode: enum_pages_hero_title_mode('hero_title_mode').notNull().default('fixed'),
    heroStyle: enum_pages_hero_style('hero_style').notNull().default('style1'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('pages_page_key_idx').on(columns.pageKey),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
  ],
)

export const pages_locales = pgTable(
  'pages_locales',
  {
    heroTitle: varchar('hero_title'),
    heroDescription: varchar('hero_description'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('pages_locales_locale_parent_id_unique').on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_rels = pgTable(
  'pages_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('pages_rels_order_idx').on(columns.order),
    index('pages_rels_parent_idx').on(columns.parent),
    index('pages_rels_path_idx').on(columns.path),
    index('pages_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [pages.id],
      name: 'pages_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'pages_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    productsID: integer('products_id'),
    needsID: integer('needs_id'),
    categoriesID: integer('categories_id'),
    linesID: integer('lines_id'),
    texturesID: integer('textures_id'),
    areasID: integer('areas_id'),
    objectivesID: integer('objectives_id'),
    intentsID: integer('intents_id'),
    zonesID: integer('zones_id'),
    treatmentsID: integer('treatments_id'),
    servicesID: integer('services_id'),
    promotionsID: integer('promotions_id'),
    programsID: integer('programs_id'),
    postsID: integer('posts_id'),
    pagesID: integer('pages_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_products_id_idx').on(columns.productsID),
    index('payload_locked_documents_rels_needs_id_idx').on(columns.needsID),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_lines_id_idx').on(columns.linesID),
    index('payload_locked_documents_rels_textures_id_idx').on(columns.texturesID),
    index('payload_locked_documents_rels_areas_id_idx').on(columns.areasID),
    index('payload_locked_documents_rels_objectives_id_idx').on(columns.objectivesID),
    index('payload_locked_documents_rels_intents_id_idx').on(columns.intentsID),
    index('payload_locked_documents_rels_zones_id_idx').on(columns.zonesID),
    index('payload_locked_documents_rels_treatments_id_idx').on(columns.treatmentsID),
    index('payload_locked_documents_rels_services_id_idx').on(columns.servicesID),
    index('payload_locked_documents_rels_promotions_id_idx').on(columns.promotionsID),
    index('payload_locked_documents_rels_programs_id_idx').on(columns.programsID),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'payload_locked_documents_rels_products_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['needsID']],
      foreignColumns: [needs.id],
      name: 'payload_locked_documents_rels_needs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['linesID']],
      foreignColumns: [lines.id],
      name: 'payload_locked_documents_rels_lines_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['texturesID']],
      foreignColumns: [textures.id],
      name: 'payload_locked_documents_rels_textures_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['areasID']],
      foreignColumns: [areas.id],
      name: 'payload_locked_documents_rels_areas_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['objectivesID']],
      foreignColumns: [objectives.id],
      name: 'payload_locked_documents_rels_objectives_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['intentsID']],
      foreignColumns: [intents.id],
      name: 'payload_locked_documents_rels_intents_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['zonesID']],
      foreignColumns: [zones.id],
      name: 'payload_locked_documents_rels_zones_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['treatmentsID']],
      foreignColumns: [treatments.id],
      name: 'payload_locked_documents_rels_treatments_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['servicesID']],
      foreignColumns: [services.id],
      name: 'payload_locked_documents_rels_services_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['promotionsID']],
      foreignColumns: [promotions.id],
      name: 'payload_locked_documents_rels_promotions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['programsID']],
      foreignColumns: [programs.id],
      name: 'payload_locked_documents_rels_programs_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const site_settings = pgTable('site_settings', {
  id: serial('id').primaryKey(),
  phone: varchar('phone'),
  whatsapp: varchar('whatsapp'),
  socials_facebook: varchar('socials_facebook'),
  socials_instagram: varchar('socials_instagram'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const site_settings_locales = pgTable(
  'site_settings_locales',
  {
    siteName: varchar('site_name').notNull().default('DOB - Department of Beauty'),
    address: varchar('address').default('Via Giovanni Rasori 9, Milano'),
    id: serial('id').primaryKey(),
    _locale: enum__locales('_locale').notNull(),
    _parentID: integer('_parent_id').notNull(),
  },
  (columns) => [
    uniqueIndex('site_settings_locales_locale_parent_id_unique').on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [site_settings.id],
      name: 'site_settings_locales_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const instagram_settings = pgTable('instagram_settings', {
  id: serial('id').primaryKey(),
  enabled: boolean('enabled').default(false),
  accessToken: varchar('access_token'),
  limit: numeric('limit', { mode: 'number' }).default(12),
  revalidateSeconds: numeric('revalidate_seconds', { mode: 'number' }).default(3600),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_users_roles = relations(users_roles, ({ one }) => ({
  parent: one(users, {
    fields: [users_roles.parent],
    references: [users.id],
    relationName: 'roles',
  }),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  roles: many(users_roles, {
    relationName: 'roles',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_products_locales = relations(products_locales, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_locales._parentID],
    references: [products.id],
    relationName: '_locales',
  }),
}))
export const relations_products_rels = relations(products_rels, ({ one }) => ({
  parent: one(products, {
    fields: [products_rels.parent],
    references: [products.id],
    relationName: '_rels',
  }),
  needsID: one(needs, {
    fields: [products_rels.needsID],
    references: [needs.id],
    relationName: 'needs',
  }),
  categoriesID: one(categories, {
    fields: [products_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
  linesID: one(lines, {
    fields: [products_rels.linesID],
    references: [lines.id],
    relationName: 'lines',
  }),
  texturesID: one(textures, {
    fields: [products_rels.texturesID],
    references: [textures.id],
    relationName: 'textures',
  }),
  mediaID: one(media, {
    fields: [products_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_products = relations(products, ({ one, many }) => ({
  coverImage: one(media, {
    fields: [products.coverImage],
    references: [media.id],
    relationName: 'coverImage',
  }),
  _locales: many(products_locales, {
    relationName: '_locales',
  }),
  _rels: many(products_rels, {
    relationName: '_rels',
  }),
}))
export const relations_needs_locales = relations(needs_locales, ({ one }) => ({
  _parentID: one(needs, {
    fields: [needs_locales._parentID],
    references: [needs.id],
    relationName: '_locales',
  }),
}))
export const relations_needs = relations(needs, ({ one, many }) => ({
  cardMedia: one(media, {
    fields: [needs.cardMedia],
    references: [media.id],
    relationName: 'cardMedia',
  }),
  _locales: many(needs_locales, {
    relationName: '_locales',
  }),
}))
export const relations_categories_locales = relations(categories_locales, ({ one }) => ({
  _parentID: one(categories, {
    fields: [categories_locales._parentID],
    references: [categories.id],
    relationName: '_locales',
  }),
}))
export const relations_categories = relations(categories, ({ one, many }) => ({
  cardMedia: one(media, {
    fields: [categories.cardMedia],
    references: [media.id],
    relationName: 'cardMedia',
  }),
  parent: one(categories, {
    fields: [categories.parent],
    references: [categories.id],
    relationName: 'parent',
  }),
  _locales: many(categories_locales, {
    relationName: '_locales',
  }),
}))
export const relations_lines_locales = relations(lines_locales, ({ one }) => ({
  _parentID: one(lines, {
    fields: [lines_locales._parentID],
    references: [lines.id],
    relationName: '_locales',
  }),
}))
export const relations_lines = relations(lines, ({ one, many }) => ({
  cardMedia: one(media, {
    fields: [lines.cardMedia],
    references: [media.id],
    relationName: 'cardMedia',
  }),
  _locales: many(lines_locales, {
    relationName: '_locales',
  }),
}))
export const relations_textures_locales = relations(textures_locales, ({ one }) => ({
  _parentID: one(textures, {
    fields: [textures_locales._parentID],
    references: [textures.id],
    relationName: '_locales',
  }),
}))
export const relations_textures = relations(textures, ({ one, many }) => ({
  cardMedia: one(media, {
    fields: [textures.cardMedia],
    references: [media.id],
    relationName: 'cardMedia',
  }),
  _locales: many(textures_locales, {
    relationName: '_locales',
  }),
}))
export const relations_areas_locales = relations(areas_locales, ({ one }) => ({
  _parentID: one(areas, {
    fields: [areas_locales._parentID],
    references: [areas.id],
    relationName: '_locales',
  }),
}))
export const relations_areas = relations(areas, ({ one, many }) => ({
  cardMedia: one(media, {
    fields: [areas.cardMedia],
    references: [media.id],
    relationName: 'cardMedia',
  }),
  _locales: many(areas_locales, {
    relationName: '_locales',
  }),
}))
export const relations_objectives_locales = relations(objectives_locales, ({ one }) => ({
  _parentID: one(objectives, {
    fields: [objectives_locales._parentID],
    references: [objectives.id],
    relationName: '_locales',
  }),
}))
export const relations_objectives = relations(objectives, ({ one, many }) => ({
  cardMedia: one(media, {
    fields: [objectives.cardMedia],
    references: [media.id],
    relationName: 'cardMedia',
  }),
  area: one(areas, {
    fields: [objectives.area],
    references: [areas.id],
    relationName: 'area',
  }),
  _locales: many(objectives_locales, {
    relationName: '_locales',
  }),
}))
export const relations_intents_locales = relations(intents_locales, ({ one }) => ({
  _parentID: one(intents, {
    fields: [intents_locales._parentID],
    references: [intents.id],
    relationName: '_locales',
  }),
}))
export const relations_intents = relations(intents, ({ many }) => ({
  _locales: many(intents_locales, {
    relationName: '_locales',
  }),
}))
export const relations_zones_locales = relations(zones_locales, ({ one }) => ({
  _parentID: one(zones, {
    fields: [zones_locales._parentID],
    references: [zones.id],
    relationName: '_locales',
  }),
}))
export const relations_zones = relations(zones, ({ many }) => ({
  _locales: many(zones_locales, {
    relationName: '_locales',
  }),
}))
export const relations_treatments_locales = relations(treatments_locales, ({ one }) => ({
  _parentID: one(treatments, {
    fields: [treatments_locales._parentID],
    references: [treatments.id],
    relationName: '_locales',
  }),
}))
export const relations_treatments_rels = relations(treatments_rels, ({ one }) => ({
  parent: one(treatments, {
    fields: [treatments_rels.parent],
    references: [treatments.id],
    relationName: '_rels',
  }),
  objectivesID: one(objectives, {
    fields: [treatments_rels.objectivesID],
    references: [objectives.id],
    relationName: 'objectives',
  }),
  areasID: one(areas, {
    fields: [treatments_rels.areasID],
    references: [areas.id],
    relationName: 'areas',
  }),
}))
export const relations_treatments = relations(treatments, ({ one, many }) => ({
  cardMedia: one(media, {
    fields: [treatments.cardMedia],
    references: [media.id],
    relationName: 'cardMedia',
  }),
  heroImage: one(media, {
    fields: [treatments.heroImage],
    references: [media.id],
    relationName: 'heroImage',
  }),
  image: one(media, {
    fields: [treatments.image],
    references: [media.id],
    relationName: 'image',
  }),
  highlightImageLeft: one(media, {
    fields: [treatments.highlightImageLeft],
    references: [media.id],
    relationName: 'highlightImageLeft',
  }),
  highlightImageRight: one(media, {
    fields: [treatments.highlightImageRight],
    references: [media.id],
    relationName: 'highlightImageRight',
  }),
  _locales: many(treatments_locales, {
    relationName: '_locales',
  }),
  _rels: many(treatments_rels, {
    relationName: '_rels',
  }),
}))
export const relations_services_locales = relations(services_locales, ({ one }) => ({
  _parentID: one(services, {
    fields: [services_locales._parentID],
    references: [services.id],
    relationName: '_locales',
  }),
}))
export const relations_services_rels = relations(services_rels, ({ one }) => ({
  parent: one(services, {
    fields: [services_rels.parent],
    references: [services.id],
    relationName: '_rels',
  }),
  treatmentsID: one(treatments, {
    fields: [services_rels.treatmentsID],
    references: [treatments.id],
    relationName: 'treatments',
  }),
}))
export const relations_services = relations(services, ({ one, many }) => ({
  category: one(treatments, {
    fields: [services.category],
    references: [treatments.id],
    relationName: 'category',
  }),
  objective: one(objectives, {
    fields: [services.objective],
    references: [objectives.id],
    relationName: 'objective',
  }),
  area: one(areas, {
    fields: [services.area],
    references: [areas.id],
    relationName: 'area',
  }),
  image: one(media, {
    fields: [services.image],
    references: [media.id],
    relationName: 'image',
  }),
  intent: one(intents, {
    fields: [services.intent],
    references: [intents.id],
    relationName: 'intent',
  }),
  zone: one(zones, {
    fields: [services.zone],
    references: [zones.id],
    relationName: 'zone',
  }),
  _locales: many(services_locales, {
    relationName: '_locales',
  }),
  _rels: many(services_rels, {
    relationName: '_rels',
  }),
}))
export const relations_promotions_locales = relations(promotions_locales, ({ one }) => ({
  _parentID: one(promotions, {
    fields: [promotions_locales._parentID],
    references: [promotions.id],
    relationName: '_locales',
  }),
}))
export const relations_promotions = relations(promotions, ({ many }) => ({
  _locales: many(promotions_locales, {
    relationName: '_locales',
  }),
}))
export const relations_programs_items_locales = relations(programs_items_locales, ({ one }) => ({
  _parentID: one(programs_items, {
    fields: [programs_items_locales._parentID],
    references: [programs_items.id],
    relationName: '_locales',
  }),
}))
export const relations_programs_items = relations(programs_items, ({ one, many }) => ({
  _parentID: one(programs, {
    fields: [programs_items._parentID],
    references: [programs.id],
    relationName: 'items',
  }),
  _locales: many(programs_items_locales, {
    relationName: '_locales',
  }),
  itemImage: one(media, {
    fields: [programs_items.itemImage],
    references: [media.id],
    relationName: 'itemImage',
  }),
}))
export const relations_programs_locales = relations(programs_locales, ({ one }) => ({
  _parentID: one(programs, {
    fields: [programs_locales._parentID],
    references: [programs.id],
    relationName: '_locales',
  }),
}))
export const relations_programs_rels = relations(programs_rels, ({ one }) => ({
  parent: one(programs, {
    fields: [programs_rels.parent],
    references: [programs.id],
    relationName: '_rels',
  }),
  servicesID: one(services, {
    fields: [programs_rels.servicesID],
    references: [services.id],
    relationName: 'services',
  }),
  treatmentsID: one(treatments, {
    fields: [programs_rels.treatmentsID],
    references: [treatments.id],
    relationName: 'treatments',
  }),
  areasID: one(areas, {
    fields: [programs_rels.areasID],
    references: [areas.id],
    relationName: 'areas',
  }),
  objectivesID: one(objectives, {
    fields: [programs_rels.objectivesID],
    references: [objectives.id],
    relationName: 'objectives',
  }),
  promotionsID: one(promotions, {
    fields: [programs_rels.promotionsID],
    references: [promotions.id],
    relationName: 'promotions',
  }),
  productsID: one(products, {
    fields: [programs_rels.productsID],
    references: [products.id],
    relationName: 'products',
  }),
  needsID: one(needs, {
    fields: [programs_rels.needsID],
    references: [needs.id],
    relationName: 'needs',
  }),
  categoriesID: one(categories, {
    fields: [programs_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
  linesID: one(lines, {
    fields: [programs_rels.linesID],
    references: [lines.id],
    relationName: 'lines',
  }),
  texturesID: one(textures, {
    fields: [programs_rels.texturesID],
    references: [textures.id],
    relationName: 'textures',
  }),
}))
export const relations_programs = relations(programs, ({ many }) => ({
  items: many(programs_items, {
    relationName: 'items',
  }),
  _locales: many(programs_locales, {
    relationName: '_locales',
  }),
  _rels: many(programs_rels, {
    relationName: '_rels',
  }),
}))
export const relations_posts_locales = relations(posts_locales, ({ one }) => ({
  _parentID: one(posts, {
    fields: [posts_locales._parentID],
    references: [posts.id],
    relationName: '_locales',
  }),
}))
export const relations_posts = relations(posts, ({ one, many }) => ({
  coverImage: one(media, {
    fields: [posts.coverImage],
    references: [media.id],
    relationName: 'coverImage',
  }),
  _locales: many(posts_locales, {
    relationName: '_locales',
  }),
}))
export const relations_pages_locales = relations(pages_locales, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_locales._parentID],
    references: [pages.id],
    relationName: '_locales',
  }),
}))
export const relations_pages_rels = relations(pages_rels, ({ one }) => ({
  parent: one(pages, {
    fields: [pages_rels.parent],
    references: [pages.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [pages_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_pages = relations(pages, ({ many }) => ({
  _locales: many(pages_locales, {
    relationName: '_locales',
  }),
  _rels: many(pages_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: 'products',
    }),
    needsID: one(needs, {
      fields: [payload_locked_documents_rels.needsID],
      references: [needs.id],
      relationName: 'needs',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    linesID: one(lines, {
      fields: [payload_locked_documents_rels.linesID],
      references: [lines.id],
      relationName: 'lines',
    }),
    texturesID: one(textures, {
      fields: [payload_locked_documents_rels.texturesID],
      references: [textures.id],
      relationName: 'textures',
    }),
    areasID: one(areas, {
      fields: [payload_locked_documents_rels.areasID],
      references: [areas.id],
      relationName: 'areas',
    }),
    objectivesID: one(objectives, {
      fields: [payload_locked_documents_rels.objectivesID],
      references: [objectives.id],
      relationName: 'objectives',
    }),
    intentsID: one(intents, {
      fields: [payload_locked_documents_rels.intentsID],
      references: [intents.id],
      relationName: 'intents',
    }),
    zonesID: one(zones, {
      fields: [payload_locked_documents_rels.zonesID],
      references: [zones.id],
      relationName: 'zones',
    }),
    treatmentsID: one(treatments, {
      fields: [payload_locked_documents_rels.treatmentsID],
      references: [treatments.id],
      relationName: 'treatments',
    }),
    servicesID: one(services, {
      fields: [payload_locked_documents_rels.servicesID],
      references: [services.id],
      relationName: 'services',
    }),
    promotionsID: one(promotions, {
      fields: [payload_locked_documents_rels.promotionsID],
      references: [promotions.id],
      relationName: 'promotions',
    }),
    programsID: one(programs, {
      fields: [payload_locked_documents_rels.programsID],
      references: [programs.id],
      relationName: 'programs',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_site_settings_locales = relations(site_settings_locales, ({ one }) => ({
  _parentID: one(site_settings, {
    fields: [site_settings_locales._parentID],
    references: [site_settings.id],
    relationName: '_locales',
  }),
}))
export const relations_site_settings = relations(site_settings, ({ many }) => ({
  _locales: many(site_settings_locales, {
    relationName: '_locales',
  }),
}))
export const relations_instagram_settings = relations(instagram_settings, () => ({}))

type DatabaseSchema = {
  enum__locales: typeof enum__locales
  enum_users_roles: typeof enum_users_roles
  enum_products_currency: typeof enum_products_currency
  enum_services_service_type: typeof enum_services_service_type
  enum_services_gender: typeof enum_services_gender
  enum_services_modality: typeof enum_services_modality
  enum_promotions_discount_type: typeof enum_promotions_discount_type
  enum_posts_category: typeof enum_posts_category
  enum_posts_status: typeof enum_posts_status
  enum_pages_page_key: typeof enum_pages_page_key
  enum_pages_hero_title_mode: typeof enum_pages_hero_title_mode
  enum_pages_hero_style: typeof enum_pages_hero_style
  users_roles: typeof users_roles
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  products: typeof products
  products_locales: typeof products_locales
  products_rels: typeof products_rels
  needs: typeof needs
  needs_locales: typeof needs_locales
  categories: typeof categories
  categories_locales: typeof categories_locales
  lines: typeof lines
  lines_locales: typeof lines_locales
  textures: typeof textures
  textures_locales: typeof textures_locales
  areas: typeof areas
  areas_locales: typeof areas_locales
  objectives: typeof objectives
  objectives_locales: typeof objectives_locales
  intents: typeof intents
  intents_locales: typeof intents_locales
  zones: typeof zones
  zones_locales: typeof zones_locales
  treatments: typeof treatments
  treatments_locales: typeof treatments_locales
  treatments_rels: typeof treatments_rels
  services: typeof services
  services_locales: typeof services_locales
  services_rels: typeof services_rels
  promotions: typeof promotions
  promotions_locales: typeof promotions_locales
  programs_items: typeof programs_items
  programs_items_locales: typeof programs_items_locales
  programs: typeof programs
  programs_locales: typeof programs_locales
  programs_rels: typeof programs_rels
  posts: typeof posts
  posts_locales: typeof posts_locales
  pages: typeof pages
  pages_locales: typeof pages_locales
  pages_rels: typeof pages_rels
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  site_settings: typeof site_settings
  site_settings_locales: typeof site_settings_locales
  instagram_settings: typeof instagram_settings
  relations_users_roles: typeof relations_users_roles
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_products_locales: typeof relations_products_locales
  relations_products_rels: typeof relations_products_rels
  relations_products: typeof relations_products
  relations_needs_locales: typeof relations_needs_locales
  relations_needs: typeof relations_needs
  relations_categories_locales: typeof relations_categories_locales
  relations_categories: typeof relations_categories
  relations_lines_locales: typeof relations_lines_locales
  relations_lines: typeof relations_lines
  relations_textures_locales: typeof relations_textures_locales
  relations_textures: typeof relations_textures
  relations_areas_locales: typeof relations_areas_locales
  relations_areas: typeof relations_areas
  relations_objectives_locales: typeof relations_objectives_locales
  relations_objectives: typeof relations_objectives
  relations_intents_locales: typeof relations_intents_locales
  relations_intents: typeof relations_intents
  relations_zones_locales: typeof relations_zones_locales
  relations_zones: typeof relations_zones
  relations_treatments_locales: typeof relations_treatments_locales
  relations_treatments_rels: typeof relations_treatments_rels
  relations_treatments: typeof relations_treatments
  relations_services_locales: typeof relations_services_locales
  relations_services_rels: typeof relations_services_rels
  relations_services: typeof relations_services
  relations_promotions_locales: typeof relations_promotions_locales
  relations_promotions: typeof relations_promotions
  relations_programs_items_locales: typeof relations_programs_items_locales
  relations_programs_items: typeof relations_programs_items
  relations_programs_locales: typeof relations_programs_locales
  relations_programs_rels: typeof relations_programs_rels
  relations_programs: typeof relations_programs
  relations_posts_locales: typeof relations_posts_locales
  relations_posts: typeof relations_posts
  relations_pages_locales: typeof relations_pages_locales
  relations_pages_rels: typeof relations_pages_rels
  relations_pages: typeof relations_pages
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_site_settings_locales: typeof relations_site_settings_locales
  relations_site_settings: typeof relations_site_settings
  relations_instagram_settings: typeof relations_instagram_settings
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
